### ISSUE TITLE
Исправление багов и моб

### ISSUE THREAD

**Issue by MelkorTheGreatest** [team-EDLIXM/Kingdom_Story#11]
@EgorCita 

- [x] исправить баг при котором , когда берешь двойной прыжок и спрыгиваешь вниз пролетаешь сквозь стену
- [x] моб эльф маг , который стреляет в героя 3 снарядами, с определенным интервалом , чтобы его можно было ударить, летящими на героя,если до него добраться , то он телепортируется за спину герою и продолжит стрелять 3 снаряда , а потом уходит на перезарядку на 2 секунды, пока он на перезарядке его нельзя бить , кд у телепорта 8 секунд +- 
- [x] звук удара добавить

если не будешь ничего делать , то скажем , что ты ничего и не делал , надеюсь тебе важна оценка)

**Comment by EgorCita** [comment]
Чтобы не было бага с проходом сквозь стены не будем делать большие разницы в высоте
