### ISSUE TITLE
Музыка и звук

### ISSUE THREAD

**Issue by MelkorTheGreatest** [team-EDLIXM/Kingdom_Story#12]
@AndrewKorzh 

- [x] написать отрывок для битвы с боссом : динамичная ненавязчивая мелодия на твое усмотрение в стилистике средневековья , фентези или что-то типа того
- [x] найди звук подбора улучшений 
- [x] звук смерти гусеницы, звук выстрела платоядным растением , а также , звуки ударов по ним и смерти тоже нужны
- [x] звуки летающего моба (жужжание ) , звуки ударов по нему и смерть

**Comment by EgorCita** [comment]
Попозже следующие задачи выдам
