### ISSUE TITLE
Нарисовать и заанимировать спрайты

### ISSUE THREAD

**Issue by MelkorTheGreatest** [team-EDLIXM/Kingdom_Story#8]
@Luizett 

- [x] #14
- [x] Окружение : деревья еще 2 вида и раскрасить те , кусты 2.3 вида , трава невысокая  (ниже кустов), бэкграунд, копья торчащие из земли , меч воткнутый , нарисуй ботинки , которые будут означать двойной прыжок,щит валяющийся
- [x] анимировать растение стреляющее,выстрел , получение урона , смерть
- [x] нарисовать костер и анимировать , который будет символизировать сохранение

**Comment by Luizett** [comment]
гусеница урон - есть 
гибель гусеница - есть

**Comment by Luizett** [comment]
ввввв
